# Generated by Django 2.2.20 on 2021-06-04 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('InvitationApp', '0001_initial'), ('InvitationApp', '0002_auto_20210601_1905'), ('InvitationApp', '0003_auto_20210601_1907'), ('InvitationApp', '0004_invitation_random_string'), ('InvitationApp', '0005_remove_invitation_random_string'), ('InvitationApp', '0006_auto_20210602_1122'), ('InvitationApp', '0007_auto_20210602_1130'), ('InvitationApp', '0008_auto_20210602_1308'), ('InvitationApp', '0009_auto_20210602_1353')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32, unique=True, verbose_name='会议名')),
                ('date', models.DateField(verbose_name='日期')),
                ('place', models.CharField(default='', max_length=32, verbose_name='地点')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32, verbose_name='姓名')),
                ('company', models.CharField(default='', max_length=32, verbose_name='公司名')),
                ('position', models.CharField(default='', max_length=32, verbose_name='职位')),
                ('phone', models.CharField(default='', max_length=12, unique=True, verbose_name='手机')),
                ('email', models.CharField(default='', max_length=32, verbose_name='邮箱')),
                ('city', models.CharField(default='', max_length=32, verbose_name='城市')),
                ('note', models.CharField(default='', max_length=32, verbose_name='备注')),
                ('confirm_number', models.CharField(default='', max_length=32, verbose_name='确认号')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='InvitationApp.Meeting')),
                ('is_sent', models.BooleanField(default=False, verbose_name='是否发送')),
                ('msg_status', models.CharField(default='', max_length=128, verbose_name='短信状态')),
                ('audit_status', models.BooleanField(default=False, verbose_name='审核状态')),
            ],
        ),
    ]
